name: CI

on:
  push:
    branches: [dev]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploying the application on the development environment
        env:
          DEV_PRIVATE_KEY: ${{ secrets.DEV_EC2_PRIVATE_KEY  }}
          DEV_HOSTNAME: ${{ secrets.DEV_HOSTNAME  }}
          DEV_USER_NAME: ${{ secrets.DEV_USER  }}

        run: |
          echo "$DEV_PRIVATE_KEY" > ec2_key.pem && chmod 600 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${DEV_USER_NAME}@${DEV_HOSTNAME} '
            DEP_HOME="~/projects/door-suisse-deployment"

            if [ ! -d $DEP_HOME ]
            then
              cd projects && git clone git@github.com:Asure-TES/door-suisse-deployment.git
            fi
            cd ~/projects/door-suisse-deployment
            git pull origin dev
            docker-compose -f docker-compose-dev.yml up -d --force-recreate --build
          '
          rm ec2_key.pem
